---
- name: Deploy Elasticsearch
  hosts: all
  sudo: true
  tasks:
  - name: Install epel repo
    yum: name=epel-release state=latest

  - name: Install python pip
    yum: name=python-pip state=latest
  
  - name: Install httplib2
    pip: name=httplib2

  - name: Install Latest Java
    yum: name=java state=latest

  - name: Install python-selinux
    yum: name=libselinux-python state=latest

  - name: Install Elasticsearch
    yum: name=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.noarch.rpm

  - name: Install Marvel Plugin
    shell: "/usr/share/elasticsearch/bin/plugin -i elasticsearch/marvel/latest -verbose"
    ignore_errors: true

  - name: Install Couchbase Transport Plugin
    shell: "/usr/share/elasticsearch/bin/plugin -install transport-couchbase -url http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.0.0/elasticsearch-transport-couchbase-2.0.0.zip"
    ignore_errors: true

  - name: Set Elasticsearch Couchbase configurations
    lineinfile: dest=/etc/elasticsearch/elasticsearch.yml line="{{ item }}" insertafter=EOF state=present
    with_items:
    - "couchbase.username: couchbase"
    - "couchbase.password: couchbase"
    - "network.publish_host: 192.168.56.42"

  - name: Start Elasticsearch
    service: name=elasticsearch state=started
    
  - wait_for: port=9200 delay=5

#  - name: Fetch Couchbase Index Template
#    fetch: src=/usr/share/elasticsearch/plugins/transport-couchbase/couchbase_template.json dest="deps/couchbase_template.json" flat=yes

  - name: Upload Couchbase Index template
#    uri: url="http://elasticsearch.demo:9200/_template/couchbase" method=PUT body="{{ lookup('file','deps/couchbase_template.json') }}"
    shell: "curl -XPUT http://127.0.0.1:9200/_template/couchbase -d @/usr/share/elasticsearch/plugins/transport-couchbase/couchbase_template.json"

  - name: Create the Couchbase index
    uri: url="http://elasticsearch.demo:9200/demo" method=PUT

  - name: Restart Elasticsearch
    service: name=elasticsearch state=restarted

  - name: Download Kibana
    shell: "wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.0-linux-x64.tar.gz -O /tmp/kibana-4.0.0-linux-x64.tar.gz"

  - name: Extract Kibana
    shell: "tar -zxvf /tmp/kibana-4.0.0-linux-x64.tar.gz -C /usr/share"

  - name: Run Kibana
    shell: "sudo nohup /usr/share/kibana-4.0.0-linux-x64/bin/kibana"
