---
- name: Deploy HDP 2.2
  hosts: all
  sudo: true
  tasks:
  - name: Install epel repo
    yum: name=epel-release state=present

  - name: Install packages
    yum: name={{item}} state=present
    with_items:
      - java
      - wget
      - ntp
      - python-pip

  - name: Update OpenSSL
    yum: name=openssl state=latest

  - name: Install Python requests module
    pip: name=requests

  - name: Run configuration script
    script: init_hdp.sh

  - name: Ensure Ambari server running
    service: name=ambari-server state=started

  - name: Run Ambari host registration script
    sudo: no
    script: blueprint.py
